local_bikes:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account
      project: caramel-thinker-478614-h2
      dataset: dbt_local_bikes_ci
      threads: 4
      keyfile: /tmp/gcp-key.json
      timeout_seconds: 1000
      location: US
